# Generated by Django 3.1.1 on 2020-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu2food',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
